"""Full forms for abbreviations used across the Mastering MongoDB module decks (modules may add their own in glossary_moduleNN.ACRONYMS)."""
from __future__ import annotations

ACRONYMS = {
    "ACID": "Atomicity, Consistency, Isolation, Durability",
    "AI": "Artificial Intelligence",
    "AMQP": "Advanced Message Queuing Protocol",
    "API": "Application Programming Interface",
    "ARO": "Azure Red Hat OpenShift",
    "ATM": "Automated Teller Machine",
    "BFF": "Backend for Frontend",
    "CD": "Continuous Delivery / Deployment",
    "CDC": "Change Data Capture",
    "CI": "Continuous Integration",
    "CI/CD": "Continuous Integration / Continuous Delivery",
    "CLI": "Command-Line Interface",
    "CORS": "Cross-Origin Resource Sharing",
    "CPU": "Central Processing Unit",
    "CQRS": "Command Query Responsibility Segregation",
    "CRUD": "Create, Read, Update, Delete",
    "CSRF": "Cross-Site Request Forgery",
    "CVE": "Common Vulnerabilities and Exposures",
    "DAST": "Dynamic Application Security Testing",
    "DB": "Database",
    "DDD": "Domain-Driven Design",
    "DDL": "Data Definition Language",
    "DI": "Dependency Injection",
    "DLQ": "Dead-Letter Queue",
    "DLT": "Dead-Letter Topic",
    "DNS": "Domain Name System",
    "DTO": "Data Transfer Object",
    "E2E": "End-to-End",
    "ESB": "Enterprise Service Bus",
    "FAQ": "Frequently Asked Questions",
    "GC": "Garbage Collection",
    "HMAC": "Hash-based Message Authentication Code",
    "HPA": "Horizontal Pod Autoscaler",
    "HTTP": "HyperText Transfer Protocol",
    "HTTPS": "HyperText Transfer Protocol Secure",
    "ID": "Identifier",
    "IDE": "Integrated Development Environment",
    "IdP": "Identity Provider",
    "IP": "Internet Protocol",
    "JAR": "Java ARchive",
    "JDBC": "Java Database Connectivity",
    "JDK": "Java Development Kit",
    "JPA": "Jakarta Persistence API",
    "JRE": "Java Runtime Environment",
    "JSON": "JavaScript Object Notation",
    "JVM": "Java Virtual Machine",
    "JWKS": "JSON Web Key Set",
    "JWT": "JSON Web Token",
    "K8s": "Kubernetes",
    "KPI": "Key Performance Indicator",
    "LLM": "Large Language Model",
    "MCP": "Model Context Protocol",
    "MDC": "Mapped Diagnostic Context",
    "MFA": "Multi-Factor Authentication",
    "MTTR": "Mean Time To Recovery",
    "MVC": "Model-View-Controller",
    "MVP": "Minimum Viable Product",
    "OAuth": "Open Authorization",
    "OCI": "Open Container Initiative",
    "OIDC": "OpenID Connect",
    "OOM": "Out Of Memory",
    "ORM": "Object-Relational Mapping",
    "OS": "Operating System",
    "OWASP": "Open Worldwide Application Security Project",
    "PAN": "Primary Account Number",
    "PCI DSS": "Payment Card Industry Data Security Standard",
    "PII": "Personally Identifiable Information",
    "PKCE": "Proof Key for Code Exchange",
    "PR": "Pull Request",
    "RAG": "Retrieval-Augmented Generation",
    "RBAC": "Role-Based Access Control",
    "REST": "Representational State Transfer",
    "RPC": "Remote Procedure Call",
    "RPS": "Requests Per Second",
    "SAST": "Static Application Security Testing",
    "SBOM": "Software Bill of Materials",
    "SHA": "Secure Hash Algorithm",
    "SKU": "Stock Keeping Unit",
    "SLA": "Service Level Agreement",
    "SLF4J": "Simple Logging Facade for Java",
    "SLI": "Service Level Indicator",
    "SLO": "Service Level Objective",
    "SNS": "Simple Notification Service",
    "SOA": "Service-Oriented Architecture",
    "SPA": "Single-Page Application",
    "SQL": "Structured Query Language",
    "SQS": "Simple Queue Service",
    "SRE": "Site Reliability Engineering",
    "SSN": "Social Security Number",
    "SSO": "Single Sign-On",
    "TLS": "Transport Layer Security",
    "TTL": "Time To Live",
    "UBI": "Universal Base Image",
    "UI": "User Interface",
    "UID": "User Identifier",
    "URI": "Uniform Resource Identifier",
    "URL": "Uniform Resource Locator",
    "UUID": "Universally Unique Identifier",
    "VM": "Virtual Machine",
    "WAF": "Web Application Firewall",
    "XML": "Extensible Markup Language",
    "YAML": "YAML Ain't Markup Language",
    "mTLS": "Mutual Transport Layer Security",
    # MongoDB course
    "BSON": "Binary JSON",
    "COLLSCAN": "Collection Scan",
    "CSRS": "Config Server Replica Set",
    "DBA": "Database Administrator",
    "ESR": "Equality, Sort, Range",
    "GUI": "Graphical User Interface",
    "IOPS": "Input/Output Operations Per Second",
    "IXSCAN": "Index Scan",
    "KMS": "Key Management Service",
    "NoSQL": "Not Only SQL",
    "RAM": "Random Access Memory",
    "RPO": "Recovery Point Objective",
    "RTO": "Recovery Time Objective",
    "SRV": "Service (DNS SRV record)",
    "UTC": "Coordinated Universal Time",
    "VPC": "Virtual Private Cloud",
    "WT": "WiredTiger",
    "oplog": "Operations log",
}
