# Exercise metadata for speaker-note generation.
# Populate when adding hands-on exercises: (module, exercise) -> metadata dict.
from __future__ import annotations

EXERCISE_META: dict[tuple[int, int], dict] = {
    (1, 1): {
        "title": "Choose the Appropriate Data Model",
        "time": "15 min",
        "type": "discussion",
        "objective": "Match application requirements to relational, document, key-value, column-family, or graph models.",
    },
    (1, 2): {
        "title": "Convert Relational Rows into a Document",
        "time": "20 min",
        "type": "hands-on",
        "objective": "Represent related rows as one MongoDB document and decide what to embed versus snapshot.",
    },
    (1, 3): {
        "title": "Explore a MongoDB Dataset",
        "time": "25 min",
        "type": "hands-on",
        "objective": "Identify databases, collections, documents, fields, arrays, and embedded objects in training_store.",
    },
    (2, 1): {
        "title": "Select a Deployment Option",
        "time": "10 min",
        "type": "discussion",
        "objective": "Choose local, containerized, self-managed, or managed-cloud MongoDB for six training and production scenarios.",
    },
    (2, 2): {
        "title": "Interpret a Connection String",
        "time": "10 min",
        "type": "discussion",
        "objective": "Label protocol, credentials, host, port, and database in a URI, and state how credentials should be stored.",
    },
    (2, 3): {
        "title": "Complete the Environment Readiness Checklist",
        "time": "10 min",
        "type": "hands-on",
        "objective": "Confirm the server, clients, connection string, ping, insert, and read before leaving Module 2.",
    },
    (2, 4): {
        "title": "Diagnose Connection Failures",
        "time": "15 min",
        "type": "discussion",
        "objective": "Map common MongoDB connection errors to a first diagnostic check, a setting or log, and a verification command.",
    },
    (2, 5): {
        "title": "Install, Connect, and Verify",
        "time": "40 min",
        "type": "hands-on",
        "objective": "Install or provision MongoDB, connect with mongosh and Compass, and prove the environment with a write-and-read test.",
    },
    (3, 1): {
        "title": "Identify Document Components",
        "time": "10 min",
        "type": "discussion",
        "objective": "Label _id, scalars, embedded documents, arrays, booleans, dates, and candidate required fields on a sample customer document.",
    },
    (3, 2): {
        "title": "Discover Application Access Patterns",
        "time": "15 min",
        "type": "discussion",
        "objective": "Turn e-commerce requirements into access patterns with frequency, required data, and a modeling implication.",
    },
    (3, 3): {
        "title": "Embed or Reference?",
        "time": "15 min",
        "type": "discussion",
        "objective": "Choose embedding or referencing for eight relationships and justify each choice from ownership, cardinality, and growth.",
    },
    (3, 4): {
        "title": "Model a Product Catalog",
        "time": "20 min",
        "type": "hands-on",
        "objective": "Design three product types in one collection with a shared core and category-specific attributes.",
    },
    (3, 5): {
        "title": "Model an Order Document",
        "time": "20 min",
        "type": "hands-on",
        "objective": "Design one order aggregate with embedded snapshots, a customer reference, required fields, and BSON types.",
    },
    (3, 6): {
        "title": "Find and Correct Schema Anti-Patterns",
        "time": "15 min",
        "type": "discussion",
        "objective": "Spot string prices, text booleans, unbounded arrays, and nonstandard dates, then rewrite the document.",
    },
    (3, 7): {
        "title": "Select a Schema Design Pattern",
        "time": "15 min",
        "type": "discussion",
        "objective": "Match seven modeling requirements to Attribute, Bucket, Subset, Computed, Extended reference, Outlier, or Polymorphic.",
    },
    (3, 8): {
        "title": "Design Collection Validation",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Write a $jsonSchema validator for required product fields, Decimal128 price, Boolean active, and Date createdAt.",
    },
    (3, 9): {
        "title": "Design a Support-Ticket Data Model",
        "time": "25 min",
        "type": "discussion",
        "objective": "Design collections, embed versus reference choices, a sample ticket document, and validation for a support-ticket workload.",
    },
    (4, 1): {
        "title": "Read Basic Documents",
        "time": "10 min",
        "type": "hands-on",
        "objective": "Retrieve documents with empty, equality, and unique-identifier filters.",
    },
    (4, 2): {
        "title": "Build Comparison Filters",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Write $gt, $gte, $lte, range, and $nin filters using Decimal128 for money.",
    },
    (4, 3): {
        "title": "Combine Logical Conditions",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Combine implicit AND, $or, and $nor into precise product and order filters.",
    },
    (4, 4): {
        "title": "Query Missing and Null Fields",
        "time": "10 min",
        "type": "hands-on",
        "objective": "Distinguish $exists, BSON null, missing fields, and incorrect types.",
    },
    (4, 5): {
        "title": "Query Arrays",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Query arrays with containment, $all, $size, $ne, and $nin.",
    },
    (4, 6): {
        "title": "Query Arrays of Documents",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Query nested arrays and use $elemMatch when two conditions must apply to the same element.",
    },
    (4, 7): {
        "title": "Design Projections",
        "time": "10 min",
        "type": "hands-on",
        "objective": "Return only required fields, including nested paths and a matching array element.",
    },
    (4, 8): {
        "title": "Sort and Paginate Results",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Sort, limit, skip, count, and retrieve distinct values with a deterministic tiebreaker.",
    },
    (4, 9): {
        "title": "Insert New Application Data",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Insert one document, several documents, a customer, and an order, then verify each write.",
    },
    (4, 10): {
        "title": "Update Product Data",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Use $set, $inc, $rename, $unset, and a filtered updateMany.",
    },
    (4, 11): {
        "title": "Modify Arrays",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Use $push, $addToSet, $each, $pull, positional $, and $[].",
    },
    (4, 12): {
        "title": "Perform an Upsert",
        "time": "10 min",
        "type": "hands-on",
        "objective": "Upsert a product by SKU so createdAt is set only on insert and updatedAt is always set.",
    },
    (4, 13): {
        "title": "Correct Unsafe Operations",
        "time": "10 min",
        "type": "discussion",
        "objective": "Explain the risk of three unsafe writes and replace them with safer alternatives.",
    },
    (4, 14): {
        "title": "Diagnose Query Errors",
        "time": "15 min",
        "type": "discussion",
        "objective": "Correct seven broken queries covering case, BSON type, dotted paths, operators, projection, $elemMatch, and update operators.",
    },
    (4, 15): {
        "title": "Lab 4.1 Dataset Verification",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Confirm training_store collections, counts, field paths, and BSON types before querying.",
    },
    (4, 16): {
        "title": "Lab 4.2 Product Query Lab",
        "time": "30 min",
        "type": "hands-on",
        "objective": "Build ten product queries covering equality, range, nested fields, tags, missing fields, types, sort, and distinct.",
    },
    (4, 17): {
        "title": "Lab 4.3 Customer and Order Query Lab",
        "time": "30 min",
        "type": "hands-on",
        "objective": "Query customers and orders by identifier, nested contact, addresses, items, status, dates, and totals.",
    },
    (4, 18): {
        "title": "Lab 4.4 Projection and Pagination Lab",
        "time": "20 min",
        "type": "hands-on",
        "objective": "Shape result documents and page through a sorted product list.",
    },
    (4, 19): {
        "title": "Lab 4.5 Insert Operations Lab",
        "time": "25 min",
        "type": "hands-on",
        "objective": "Insert a product, several products, a customer, and a related order; inspect ids and types.",
    },
    (4, 20): {
        "title": "Lab 4.6 Update Operations Lab",
        "time": "30 min",
        "type": "hands-on",
        "objective": "Practice $set, $unset, $inc, $min, $max, $rename, nested updates, and updateMany with the preview-update-verify loop.",
    },
    (4, 21): {
        "title": "Lab 4.7 Array Manipulation Lab",
        "time": "30 min",
        "type": "hands-on",
        "objective": "Add, unique-add, batch-add, and remove tags; update one, all, and filtered array elements on an order.",
    },
    (4, 22): {
        "title": "Lab 4.8 Replace and Upsert Lab",
        "time": "20 min",
        "type": "hands-on",
        "objective": "Compare $set, replaceOne, and a repeated upsert on a copied test document.",
    },
    (4, 23): {
        "title": "Lab 4.9 Delete Operations Lab",
        "time": "20 min",
        "type": "hands-on",
        "objective": "Delete only temporary lab records using a preview-count-delete-verify sequence.",
    },
    (4, 24): {
        "title": "Lab 4.10 Integrated CRUD Challenge",
        "time": "45 min",
        "type": "hands-on",
        "objective": "Walk a store scenario from new product through order updates to a verified soft-delete.",
    },
    (4, 25): {
        "title": "Module 4 Practical Challenge",
        "time": "30–45 min",
        "type": "hands-on",
        "objective": "Turn business requests into a verified query script with safety controls.",
    },
    (5, 1): {
        "title": "Arrange Pipeline Stages",
        "time": "10 min",
        "type": "discussion",
        "objective": "Put aggregation stages in the order required for a correct top-five-product report.",
    },
    (5, 2): {
        "title": "Build a $match Stage",
        "time": "10 min",
        "type": "hands-on",
        "objective": "Write $match stages for paid orders, high-value orders, active products, review dates, and customer provinces.",
    },
    (5, 3): {
        "title": "Reshape Documents with $project",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Rename product fields and build a nested report document without _id.",
    },
    (5, 4): {
        "title": "Create Calculated Fields",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Add line revenue, shipping-safe totals, full names, value class, and reporting month.",
    },
    (5, 5): {
        "title": "Group and Calculate Totals",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Group active products by category and compute count, average, min, and max price.",
    },
    (5, 6): {
        "title": "Group by Multiple Dimensions",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Group orders by payment status and fulfillment status with count, revenue, and average.",
    },
    (5, 7): {
        "title": "Analyze Arrays with $unwind",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Unwind paid order items and compute units, revenue, and order count per SKU.",
    },
    (5, 8): {
        "title": "Build a Top-N Report",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Build top-N reports for customers, products, orders, and categories using group, sort, and limit.",
    },
    (5, 9): {
        "title": "Join Related Collections",
        "time": "20 min",
        "type": "hands-on",
        "objective": "Lookup customers from orders, format names, sort by total, and keep unmatched orders.",
    },
    (5, 10): {
        "title": "Build a $facet Report",
        "time": "20 min",
        "type": "hands-on",
        "objective": "Return one document with product totals, category counts, average price, price bands, and top expensive products.",
    },
    (5, 11): {
        "title": "Correct a Broken Pipeline",
        "time": "15 min",
        "type": "hands-on",
        "objective": "Diagnose aggregation mistakes and rewrite the pipeline so the top product by revenue is correct.",
    },
    (5, 12): {
        "title": "Optimize a Pipeline",
        "time": "15 min",
        "type": "discussion",
        "objective": "Rewrite an expensive pipeline so it stays equivalent but filters earlier and looks up later.",
    },
    (5, 13): {
        "title": "Executive Sales Summary",
        "time": "30-45 min",
        "type": "hands-on",
        "objective": "Produce a date-bounded executive report covering revenue, monthly trend, products, customers, categories, and price bands.",
    },
    (6, 1): {
        "title": "Identify Candidate Indexes",
        "time": "15 min",
        "type": "discussion",
        "objective": "Name the fields that belong in an index for six recurring training_store queries.",
    },
    (6, 2): {
        "title": "Select Single or Compound Indexes",
        "time": "15 min",
        "type": "discussion",
        "objective": "Classify each requirement as a single-field, compound, specialized, or not-enough-evidence index.",
    },
    (6, 3): {
        "title": "Arrange Compound-Index Fields",
        "time": "15 min",
        "type": "discussion",
        "objective": "Propose a compound-index field order using Equality–Sort–Range.",
    },
    (6, 4): {
        "title": "Apply Equality–Sort–Range",
        "time": "15 min",
        "type": "discussion",
        "objective": "Label equality, sort, and range fields on several query shapes and propose compound indexes.",
    },
    (6, 5): {
        "title": "Identify Index Prefixes",
        "time": "10 min",
        "type": "discussion",
        "objective": "State which query prefixes a compound index can support directly.",
    },
    (6, 6): {
        "title": "Select Specialized Index Types",
        "time": "15 min",
        "type": "discussion",
        "objective": "Match requirements to unique, partial, sparse, TTL, text, wildcard, geospatial, or hashed indexes.",
    },
    (6, 7): {
        "title": "Interpret Explain Output",
        "time": "20 min",
        "type": "discussion",
        "objective": "Read COLLSCAN versus IXSCAN, examined counts, extra sorts, and selectivity signals.",
    },
    (6, 8): {
        "title": "Identify Covered Queries",
        "time": "15 min",
        "type": "discussion",
        "objective": "Decide which query and projection combinations may be covered by a given index.",
    },
    (6, 9): {
        "title": "Find Redundant Indexes",
        "time": "15 min",
        "type": "discussion",
        "objective": "Spot overlapping prefixes without dropping an index on appearance alone.",
    },
    (6, 10): {
        "title": "Balance Read and Write Performance",
        "time": "15 min",
        "type": "discussion",
        "objective": "Plan evidence, hide-testing, and metrics for a write-heavy over-indexed workload.",
    },
    (6, 11): {
        "title": "Correct Indexing Anti-Patterns",
        "time": "15 min",
        "type": "discussion",
        "objective": "Rewrite unsafe indexing habits as safer, evidence-based practices.",
    },
    (6, 12): {
        "title": "Build an Indexing Recommendation",
        "time": "20 min",
        "type": "discussion",
        "objective": "Write a recommendation with query shape, proposed index, cost, validation, and rollback.",
    },
    (6, 13): {
        "title": "E-Commerce Index Review",
        "time": "30–45 min",
        "type": "discussion",
        "objective": "Recommend indexes for ten application query patterns, including specialized types and overlap checks.",
    },
    (7, 1): {
        "title": "Replication or Sharding?",
        "time": "10 min",
        "type": "discussion",
        "objective": "Choose replication, sharding, both, or neither yet for six architecture requirements.",
    },
    (7, 2): {
        "title": "Label a Replica-Set Architecture",
        "time": "10 min",
        "type": "discussion",
        "objective": "Label application, driver, primary, secondaries, oplog flow, heartbeats, and read/write paths.",
    },
    (7, 3): {
        "title": "Trace a Replicated Write",
        "time": "15 min",
        "type": "discussion",
        "objective": "Sequence a write from the client through oplog application and write-concern acknowledgment.",
    },
    (7, 4): {
        "title": "Sequence a Failover",
        "time": "15 min",
        "type": "discussion",
        "objective": "Arrange detection, election, new primary, driver discovery, and application retry.",
    },
    (7, 5): {
        "title": "Select Read and Write Settings",
        "time": "20 min",
        "type": "discussion",
        "objective": "Choose read preference, read concern, and write concern for six business operations.",
    },
    (7, 6): {
        "title": "Diagnose Replication Lag",
        "time": "15 min",
        "type": "discussion",
        "objective": "Match lag symptoms to cause, impact, evidence, and a first corrective action.",
    },
    (7, 7): {
        "title": "Label a Sharded Cluster",
        "time": "10 min",
        "type": "discussion",
        "objective": "Label mongos, configuration servers, shards, replica-set members, metadata, and query flow.",
    },
    (7, 8): {
        "title": "Evaluate Shard-Key Candidates",
        "time": "20 min",
        "type": "discussion",
        "objective": "Score order shard-key candidates and recommend one with remaining risks.",
    },
    (7, 9): {
        "title": "Targeted or Scatter-Gather?",
        "time": "15 min",
        "type": "discussion",
        "objective": "Classify queries as targeted, multi-shard, scatter-gather, or insufficient information.",
    },
    (7, 10): {
        "title": "Compare Ranged and Hashed Sharding",
        "time": "15 min",
        "type": "discussion",
        "objective": "Evaluate ranged versus hashed sharding for equality, ranges, sequential writes, and locality.",
    },
    (7, 11): {
        "title": "Diagnose Hotspot Risks",
        "time": "15 min",
        "type": "discussion",
        "objective": "Review five hotspot patterns and propose a mitigation for each.",
    },
    (7, 12): {
        "title": "Design a Scalable Deployment",
        "time": "25 min",
        "type": "discussion",
        "objective": "Design availability, sharding, shard key, routing, and residency for a 24/7 order platform.",
    },
    (7, 13): {
        "title": "Scale the E-Commerce Order Platform",
        "time": "30–45 min",
        "type": "discussion",
        "objective": "Produce availability, sharding, shard-key, routing, and operational plans from a standalone starting point.",
    },
    (8, 1): {
        "title": "Review a Document Model",
        "time": "15 min",
        "type": "discussion",
        "objective": "Evaluate an order-shaped document for access patterns, snapshots, types, growth, sensitive data, and validation.",
    },
    (8, 2): {
        "title": "Find the Schema Anti-Patterns",
        "time": "15 min",
        "type": "discussion",
        "objective": "Identify unbounded arrays, textual prices, inconsistent names, and related anti-patterns, then sketch a repair.",
    },
    (8, 3): {
        "title": "Review a Query and Projection",
        "time": "15 min",
        "type": "discussion",
        "objective": "Rewrite a broad find into a selective, projected, sorted, limited query with an ESR index.",
    },
    (8, 4): {
        "title": "Optimize an Aggregation Pipeline",
        "time": "20 min",
        "type": "discussion",
        "objective": "Reorder a lookup-first pipeline and avoid double-counting parent totals after $unwind.",
    },
    (8, 5): {
        "title": "Rationalize an Index Portfolio",
        "time": "20 min",
        "type": "discussion",
        "objective": "Map overlapping prefixes, low-selectivity keys, and a hide-then-monitor removal plan.",
    },
    (8, 6): {
        "title": "Design Least-Privilege Roles",
        "time": "20 min",
        "type": "discussion",
        "objective": "Define permit and deny operations for application, reporting, support, monitoring, backup, and DBA identities.",
    },
    (8, 7): {
        "title": "Identify Security Risks",
        "time": "15 min",
        "type": "discussion",
        "objective": "Rank public exposure, shared admin, secrets in git, missing TLS, open backups, and prod-in-dev, then mitigate.",
    },
    (8, 8): {
        "title": "Define RPO and RTO",
        "time": "15 min",
        "type": "discussion",
        "objective": "Set recovery objectives, backup frequency, method, and validation for catalog, customers, orders, payments, and reviews.",
    },
    (8, 9): {
        "title": "Design a Monitoring Dashboard",
        "time": "20 min",
        "type": "discussion",
        "objective": "Select essential on-call metrics with a purpose for each tile and drop vanity signals.",
    },
    (8, 10): {
        "title": "Set Alert Priorities",
        "time": "15 min",
        "type": "discussion",
        "objective": "Classify operational alerts and attach a first action for critical and high events.",
    },
    (8, 11): {
        "title": "Diagnose an Operational Incident",
        "time": "20 min",
        "type": "discussion",
        "objective": "Explain post-release slowness from a filter change using examined-document growth, not failover.",
    },
    (8, 12): {
        "title": "Create an Operational Runbook",
        "time": "20 min",
        "type": "discussion",
        "objective": "Write a twelve-section runbook for one named MongoDB alert.",
    },
    (8, 13): {
        "title": "Complete a Production-Readiness Assessment",
        "time": "25 min",
        "type": "discussion",
        "objective": "Score a fictional deployment and classify it as ready, ready with conditions, or not ready.",
    },
    (8, 14): {
        "title": "Production-Readiness Review for training_store",
        "time": "45 min",
        "type": "discussion",
        "objective": "Produce a six-part action plan and an evidence-based production-readiness classification.",
    },
}
