"""Authored Kahoot banks for Mastering MongoDB (decks/pptx_new).

Each item is (question, a1, a2, a3, a4, correct) with correct in 1–4.
Kahoot limits: question ≤95 chars, answers ≤60 chars.
Answer options are padded to equal length so players cannot guess by length.
Correct slot is authored as 1; regenerate_kahoot_xlsx shuffles it per question.

Questions are conceptual and follow the module decks. They do not cite
slide numbers or lab steps.
"""

from __future__ import annotations

BANK: dict[int, list[tuple[str, str, str, str, str, int]]] = {}

MODULE_TITLES: dict[int, str] = {
    1: "Introduction to NoSQL Databases",
    2: "Installation and Setup",
    3: "Data Modeling with MongoDB",
    4: "The MongoDB Query Language",
    5: "The Aggregation Framework",
    6: "Indexing and Query Performance",
    7: "Introduction to Replication and Sharding",
    8: "Best Practices, Security, and Troubleshooting",
}

ANSWER_MAX = 60
# Longest-first so padding hits the target length exactly.
_PADS = (
    " in this platform",
    " in this design",
    " in this case",
    " in this env",
    " at runtime",
    " in prod",
    " today",
    " here",
    " now",
    " ·",
    "·",
)


def q(
    question: str, a1: str, a2: str, a3: str, a4: str, correct: int
) -> tuple[str, str, str, str, str, int]:
    return (question, a1, a2, a3, a4, correct)


def day_for_module(module: int) -> int:
    if module <= 3:
        return 1
    if module <= 5:
        return 2
    return 3


def _pad_to(text: str, target: int) -> str:
    if len(text) > ANSWER_MAX:
        text = text[:ANSWER_MAX]
    target = min(target, ANSWER_MAX)
    if len(text) >= target:
        return text
    while len(text) < target:
        need = target - len(text)
        pad = next((p for p in _PADS if len(p) <= need), None)
        if pad is None:
            break
        text += pad
    return text


def _equalize(answers: list[str]) -> list[str]:
    capped = [a[:ANSWER_MAX] for a in answers]
    target = max(len(a) for a in capped)
    return [_pad_to(a, target) for a in capped]


def as_questions(module: int) -> list[dict]:
    items = []
    for question, a1, a2, a3, a4, correct in BANK[module]:
        answers = _equalize([a1, a2, a3, a4])
        items.append({"question": question, "answers": answers, "correct": correct})
    return items


# ---------------------------------------------------------------------------
# Module 1 — Introduction to NoSQL Databases
# ---------------------------------------------------------------------------

BANK[1] = [
    q("NoSQL means Not Only SQL. What does that communicate?",
      "Other data models can sit beside relational SQL",
      "Relational databases should all be retired now",
      "Every application must stop using SQL joins",
      "Only graph stores are allowed in production", 1),
    q("One order page joins five tables. What is the main cost?",
      "Many lookups just to rebuild one screen",
      "Too many independently owned databases",
      "Excess copies of one row on one server",
      "Automatic loss of every foreign-key check", 1),
    q("Why do teams want a flexible document schema?",
      "New fields can arrive without a migration",
      "Every column type is fixed before insert",
      "Foreign keys must be declared for arrays",
      "Joins get faster when the schema is rigid", 1),
    q("Which model stores one opaque value per exact key?",
      "Key-value, for sessions, carts and cache",
      "Graph, for walking many relationships",
      "Column-family, for wide sparse event rows",
      "Relational, when integrity and joins matter", 1),
    q("Fraud checks walk many relationships. Best starting model?",
      "Graph: nodes, relationships and properties",
      "Key-value: one blob fetched by a single key",
      "Column-family: huge writes by a row key",
      "Document: one self-contained catalog record", 1),
    q("What does BSON add that plain JSON does not?",
      "Types such as dates, decimals and ObjectIds",
      "A required SQL schema on every collection",
      "Automatic joins across every related table",
      "A rule that every field name must be unique", 1),
    q("Where do documents live inside a MongoDB database?",
      "In a collection, inside that database",
      "In a table joined by a foreign key",
      "In a graph of nodes and edges only",
      "In one opaque value addressed by a key", 1),
    q("A relational row maps most closely to which idea?",
      "A document, which may also nest arrays",
      "A collection that holds a single value",
      "A foreign key that always points at SQL",
      "A stored procedure that rebuilds the page", 1),
    q("How does an order avoid a join for its line items?",
      "The items are embedded in the order document",
      "Five tables are still required on every read",
      "Each item is stored only as a graph edge",
      "Line items live in a separate SQL view", 1),
    q("A laptop and a book share one collection but differ. Why is that valid?",
      "A flexible schema allows different attributes",
      "Every document must have identical fields",
      "A collection cannot mix more than one type",
      "BSON forbids optional fields on a product", 1),
    q("Which process stores the data and answers requests?",
      "mongod, the MongoDB server process",
      "mongosh, the interactive command shell",
      "Compass, the graphical document browser",
      "A driver library inside application code", 1),
    q("What is WiredTiger in this architecture?",
      "The default storage engine behind mongod",
      "The shell used to type queries by hand",
      "The cloud UI that draws replica-set maps",
      "The driver that applications import", 1),
    q("How do a replica set and a sharded cluster differ?",
      "Copies for availability versus pieces for scale",
      "Both only add CPU on a single larger server",
      "Shards copy data; replicas split collections",
      "Neither changes how clients send a query", 1),
    q("When is MongoDB often a weaker first choice?",
      "Deep graph traversal or a pure session cache",
      "Catalogs whose attributes keep on changing",
      "Orders read together with their line items",
      "Schemas that gain fields without a migration", 1),
    q("People say schemaless means no design. What is the reality?",
      "A flexible schema still needs a deliberate model",
      "Validation is impossible once field types vary",
      "SQL becomes obsolete the day documents arrive",
      "Every field must be fixed before the first write", 1),
]


# ---------------------------------------------------------------------------
# Module 2 — Installation and Setup
# ---------------------------------------------------------------------------

BANK[2] = [
    q("A classroom laptop must work offline. Which deployment fits?",
      "Local Community Edition or a local container",
      "Atlas only, because TLS is always required",
      "A shared production cluster for every student",
      "A graph store, because joins are not needed", 1),
    q("What does mongod do that mongosh does not?",
      "It stores the data and listens for clients",
      "It only prints query results, then exits",
      "It draws documents in a graphical browser",
      "It is the library imported by app code", 1),
    q("Does closing mongosh stop the database?",
      "No. mongod is a separate process and keeps running",
      "Yes. The shell and the server are one program",
      "Yes. Compass must stay open or mongod exits",
      "No. Only an Atlas cluster survives a closed shell", 1),
    q("What is the default local address for Community mongod?",
      "localhost port 27017, private to this machine",
      "An Atlas SRV hostname that requires TLS",
      "Port 80 on every network interface",
      "A DNS seed list that omits the port", 1),
    q("Does use training_store make the database show up immediately?",
      "No. It appears when the first write creates it",
      "Yes. use creates it even with no documents",
      "Only after Compass refreshes its sidebar",
      "Only after authentication is turned on", 1),
    q("What does a mongodb+srv:// connection string change?",
      "DNS supplies the members, so the URI has no port",
      "It turns off TLS and skips authentication",
      "It binds mongod to localhost only",
      "It creates the database before any write", 1),
    q("Who should an Atlas database user be?",
      "A least-privilege user, not your Atlas login",
      "The same account that opens the Atlas UI",
      "A cluster admin shared in the class chat",
      "Nobody, because Atlas does not use auth", 1),
    q("mongosh says connection refused on localhost:27017. First check?",
      "Is mongod running and listening on that port?",
      "Is the password percent-encoded in the URI?",
      "Is the Atlas IP access list blocking you?",
      "Did the filter use the wrong field name?", 1),
    q("Local ping works, but a remote client times out. Likely cause?",
      "Firewall, routing, or the Atlas IP access list",
      "Closing the shell stopped the mongod process",
      "The filter was case-sensitive and missed rows",
      "A price was stored as a string, not a decimal", 1),
    q("Authentication versus authorization means?",
      "Who you are, versus what you are allowed to do",
      "Which port you use, versus the database name",
      "TLS on the wire, versus the data directory path",
      "A replica set, versus a sharded cluster", 1),
    q("A fresh local install has access control off. When is that tolerable?",
      "Only while mongod stays bound to localhost",
      "Whenever the laptop joins a public network",
      "On every Atlas cluster, to keep class simple",
      "If the password is committed in the Git repo", 1),
    q("Where should a shared connection string keep the password?",
      "Out of chat, screenshots, scripts and Git",
      "On the slide so the whole class can connect",
      "Inside a URI that is committed to the repo",
      "In a screenshot of the Compass connect dialog", 1),
    q("mongosh, Compass and a driver all point at one deployment. They share?",
      "The same data on that one running server",
      "Separate copies that never see each other's writes",
      "Writes from the shell only; Compass is read-only",
      "Direct edits to the data files, bypassing mongod", 1),
    q("db.runCommand({ ping: 1 }) returns { ok: 1 }. What did you prove?",
      "The server answered; still prove a write and a read",
      "Backups, indexes and authentication are finished",
      "The replica set has already elected a primary",
      "The full training_store dataset is loaded", 1),
    q("What does bindIp control?",
      "Which addresses mongod will accept connections on",
      "Which database role the user is granted",
      "How large the WiredTiger cache may grow",
      "Which field is used as the shard key", 1),
]


# ---------------------------------------------------------------------------
# Module 3 — Data Modeling with MongoDB
# ---------------------------------------------------------------------------

BANK[3] = [
    q("What should decide the shape of a document?",
      "The reads and writes the application does often",
      "One collection for every old relational table",
      "One collection for each screen in the UI",
      "Whatever field order Compass happens to show", 1),
    q("Which BSON type should store a product price?",
      "Decimal128, so money is not a binary float",
      "String, so a currency symbol can be included",
      "Boolean, because a price is either set or not",
      "Date, because catalog prices change over time", 1),
    q("Why is a price stored as the string 49.99 a problem?",
      "Sorts and math then treat the price as text",
      "BSON rejects every string at insert time",
      "Strings are always unique inside a collection",
      "String fields cannot be longer than four characters", 1),
    q("Why are a customer's few addresses embedded?",
      "They are bounded, owned, and read with the profile",
      "The address list grows without any limit",
      "The same address is shared by many customers",
      "Every address read must use a $lookup", 1),
    q("Why are product reviews referenced instead of embedded?",
      "The list keeps growing and is not only one page",
      "Each product has exactly one review document",
      "Reviews are always smaller than 16 MiB",
      "A product document cannot contain an array", 1),
    q("What is the hard size limit of one BSON document?",
      "16 MiB, so unbounded arrays should not be embedded",
      "1 KB, so only scalar fields are allowed",
      "There is no limit, so embed every related collection",
      "64 bytes, which is why _id must be an ObjectId", 1),
    q("Read together, bounded, and the same lifecycle. What should you do?",
      "Embed the related data in the parent document",
      "Always reference it and join with $lookup",
      "Store it only in a key-value session cache",
      "Put each field in its own collection", 1),
    q("An order references the customer but embeds line items. Why embed items?",
      "Items are bounded and shown with that order",
      "The same items are shared by every order",
      "The item list grows without limit after checkout",
      "Items must stay in their own SQL table", 1),
    q("The order stores the unit price from checkout. Why?",
      "It is a snapshot; later catalog prices must not change it",
      "The product document is deleted at checkout",
      "Decimal128 cannot be stored on the product",
      "The products collection is not allowed to change", 1),
    q("Why is one collection per old table an anti-pattern?",
      "Each page is rebuilt with extra lookups",
      "Documents then become too small to index",
      "MongoDB allows only one collection per database",
      "Validation cannot run on embedded fields", 1),
    q("customerId, customer_id and custId appear together. What breaks?",
      "A query on one spelling misses the other documents",
      "MongoDB treats those three names as one field",
      "One index automatically covers all three names",
      "Validation merges them into a single BSON type", 1),
    q("When does the subset pattern fit?",
      "The page needs a few hot items, not the full history",
      "Every event must live in one growing array",
      "A value is calculated once and read many times",
      "Many optional attributes should share one index", 1),
    q("Why store ratingAvg on the product (computed pattern)?",
      "So each page view does not average every review",
      "So every review stays embedded on the product",
      "So every catalog read must run a $lookup",
      "So the collection no longer needs validation", 1),
    q("validationAction error versus warn means?",
      "error rejects the write; warn stores it and logs",
      "error drops the collection; warn drops the index",
      "error turns off auth; warn turns off TLS",
      "error shards the data; warn starts an election", 1),
    q("What is the safe first step when a schema must change?",
      "Add an optional field that old readers can ignore",
      "Rename every field in one required migration",
      "Drop the collection before writing the new shape",
      "Set validation to error before any backfill", 1),
]


# ---------------------------------------------------------------------------
# Module 4 — The MongoDB Query Language
# ---------------------------------------------------------------------------

BANK[4] = [
    q("How do findOne() and find() differ?",
      "One document or null, versus a cursor of every match",
      "find() returns null; findOne() always scans all docs",
      "They differ only by which index they must use",
      "findOne() deletes the match; find() updates it", 1),
    q("Filters are case-sensitive. Why can Category: LAPTOP miss?",
      "The stored field is category, not Category",
      "String equality in MongoDB ignores case",
      "Only documents that lack an _id are skipped",
      "Equality never matches a string field", 1),
    q("Where does a comparison operator belong?",
      "Inside the field: price greater than a value",
      "Outside the field, wrapping the field name",
      "Only in a $project stage, never in find()",
      "Only as a sort direction of 1 or -1", 1),
    q("Two conditions separated by commas in a filter mean?",
      "AND: every listed condition must be true",
      "OR: any one condition is enough to match",
      "NOR: reject the document if any one matches",
      "NOT: invert the entire query document", 1),
    q("A filter of phone equal to null matches which documents?",
      "Explicit null and documents where phone is missing",
      "Only documents whose phone is the text null",
      "Only documents whose price is a Decimal128",
      "Every document stored in that collection", 1),
    q("Why must the path attributes.memoryGB be quoted in a filter?",
      "An unquoted dot is a syntax error, not a path",
      "Quoted paths are forbidden from using an index",
      "Dot notation works only inside $group",
      "Quotes force a full collection scan", 1),
    q("tags equal to wireless versus matching the whole array means?",
      "Contains that value, versus the array is exactly equal",
      "Both require every tag and the same array length",
      "Both ignore order and duplicate elements",
      "$size must be used before either form can match", 1),
    q("Why use $elemMatch on an array of order items?",
      "One array element must satisfy every condition",
      "It updates every item in the array at once",
      "It replaces the entire order document",
      "It counts matches without reading documents", 1),
    q("What happens if you $push the same value twice?",
      "The value is stored twice; $addToSet would keep one",
      "The second $push is rejected as a duplicate",
      "$addToSet appends duplicates and $push does not",
      "Neither operator is allowed to change an array", 1),
    q("How is replaceOne() different from $set?",
      "replaceOne rewrites the body; only _id survives",
      "$set deletes every field you do not name",
      "replaceOne can change only one nested field",
      "$set does nothing unless the write is an upsert", 1),
    q("An upsert runs and the filter matches nothing. What happens?",
      "A new document is inserted from the update",
      "The command throws and rolls back the collection",
      "Every document in the collection is updated",
      "Only matchedCount increases; nothing is inserted", 1),
    q("matchedCount is 1 and modifiedCount is 0. What happened?",
      "A document matched, but the new value was already there",
      "The server rejected the write as a conflict",
      "Every document in the collection was changed",
      "The filter did not match any document", 1),
    q("What is the safe order for a delete?",
      "Count and preview the filter, then delete that set",
      "deleteMany with an empty filter, to clear the way",
      "Drop the index on that field, then delete",
      "replaceOne so the document body becomes empty", 1),
    q("A projection that includes name and price also returns?",
      "_id, unless the projection also sets _id to 0",
      "Every other field still stored on the document",
      "Nothing, because inclusion requires $project",
      "Only fields that already have an index", 1),
    q("Why combine sort, skip and limit?",
      "To order the matches and return one page",
      "To create a unique index on the sort field",
      "To join two collections in one round trip",
      "To validate documents with $jsonSchema", 1),
]


# ---------------------------------------------------------------------------
# Module 5 — The Aggregation Framework
# ---------------------------------------------------------------------------

BANK[5] = [
    q("How is aggregate() different from find()?",
      "It computes new results through a pipeline of stages",
      "It can only update documents, never read them",
      "It always returns the same shape as find()",
      "It ignores every filter and it cannot sort", 1),
    q("What does each pipeline stage receive?",
      "The documents produced by the previous stage",
      "The original collection, ignoring earlier stages",
      "Only the _id index, never the documents",
      "A single SQL row produced by a joined table", 1),
    q("You need paid revenue per customer. Which stage order works?",
      "Match paid orders first, then group them",
      "Group every order, then the paid filter is optional",
      "Limit to one document, then sort the rest",
      "Lookup the catalog before any filter", 1),
    q("What leaves a $group stage?",
      "Only the group key and the accumulators",
      "Every original field, plus the new totals",
      "Only the one array element that matched",
      "An uncomputed cursor over the source collection", 1),
    q("How should a top-N report be ordered?",
      "Sort the whole stream, then keep N documents",
      "Limit first, then sort that small sample",
      "Group before filtering the source documents",
      "Unwind after the limit so extra items vanish", 1),
    q("What does $unwind do to an order with three items?",
      "It emits three documents, one per array element",
      "It deletes two of the three line items",
      "It sums the order total into one field",
      "It joins the customer collection automatically", 1),
    q("Why can summing the order total after $unwind be wrong?",
      "The same order total is added once per line",
      "Unwind removes duplicate line items first",
      "The total is then covered by the _id index",
      "The pipeline turns into a single find()", 1),
    q("What does $lookup add to each input document?",
      "An array of matching documents from the other collection",
      "Exactly one embedded document, or else null",
      "A new collection that replaces the input",
      "A unique index built on the foreign key", 1),
    q("Why group customer spending before looking up names?",
      "One lookup per customer instead of one per order",
      "$lookup is illegal after a $group stage",
      "Customer names exist only before grouping",
      "The join then has to scan every product", 1),
    q("What is true of the sub-pipelines inside $facet?",
      "Each sees the same input and the results share one document",
      "Each must write to a different collection",
      "They run only when the first branch is empty",
      "They remove the need for an earlier $match", 1),
    q("Why put $match as early as the logic allows?",
      "Later stages then process fewer documents",
      "Only the last stage is allowed to filter",
      "$match can never use an index",
      "Grouping is illegal after a filter", 1),
    q("In an expression, how do $total and the word total differ?",
      "$total reads a field; total is a literal string",
      "They always refer to the same stored field",
      "total reads the field and $total is plain text",
      "Both are valid only as $group accumulators", 1),
    q("How are dates stored, and what do monthly reports need?",
      "UTC instants; format a local calendar month for the report",
      "Local wall time, with no time zone at all",
      "Display strings such as September 20, 2026",
      "Integers that count days and ignore the time", 1),
    q("What is the $bucket stage for?",
      "Grouping values into ranges the business defines",
      "Joining two collections together on _id",
      "Deleting session documents after they expire",
      "Choosing which replica may serve a read", 1),
    q("A pipeline returns quickly but the total looks wrong. What should you do?",
      "Compare it with a control total from another query",
      "Trust the first stage that returns any rows",
      "Remove $match so every document is included",
      "Skip explain, because pipelines are not planned", 1),
]


# ---------------------------------------------------------------------------
# Module 6 — Indexing and Query Performance
# ---------------------------------------------------------------------------

BANK[6] = [
    q("How does a collection scan differ from an index scan?",
      "Every document is tested; an index narrows the search",
      "An index scan always reads more documents",
      "A collection scan uses _id; an index scan uses none",
      "They differ only in the sort direction used", 1),
    q("What is an index in MongoDB?",
      "A sorted tree of keys, each pointing at a document",
      "A full extra copy of every field in the collection",
      "A backup kept on another replica-set member",
      "A validator that rejects the wrong BSON type", 1),
    q("What is true of the _id index?",
      "It is created automatically and it is unique",
      "It appears only after you call createIndex",
      "It is a TTL index that deletes old documents",
      "It is a text index over every string field", 1),
    q("Why hide an index before you drop it?",
      "The planner stops using it, and you can still unhide it",
      "Hiding immediately deletes the index and the data",
      "Hiding rebuilds every index on the collection",
      "Hiding changes the shard key with no downtime", 1),
    q("Index { category: 1, price: 1 } best serves which query?",
      "Equality on category, then a price range or sort",
      "A filter on price alone, as if price led the index",
      "Any field order, including price then category",
      "Only a sort on the _id field and nothing else", 1),
    q("What does Equality, Sort, Range tell you to do?",
      "Put equality fields first, then the sort, then the range",
      "Put the range field first so the scan stays short",
      "Leave sort fields out of the index entirely",
      "Use equality fields only inside a partial filter", 1),
    q("The prefix rule says a compound index can serve?",
      "Queries on its leading fields, in that order",
      "Any field in the index, equally well",
      "A covered query only when _id is returned",
      "A unique constraint on a different field", 1),
    q("A multikey index on an array such as tags stores?",
      "One index entry for each value in the array",
      "One entry for the whole array as a single blob",
      "Nothing, because arrays cannot be indexed",
      "Only the first element of the array", 1),
    q("What does a unique index on sku guarantee?",
      "The server rejects a second document with that SKU",
      "Only the application must check for duplicates",
      "Only a document with a missing sku is rejected",
      "Uniqueness applies to _id and to nothing else", 1),
    q("A partial index whose filter is active: true contains?",
      "Only documents that match that filter",
      "Every document, with inactive ones hidden",
      "A timer that deletes inactive products",
      "Only documents where the field is missing", 1),
    q("Where does a TTL index belong?",
      "On expiring data such as sessions, not on orders",
      "On every collection, so documents stay small",
      "On _id, replacing the default index",
      "On the shard key, so chunks expire", 1),
    q("How do executionStats and queryPlanner differ?",
      "executionStats runs the query; queryPlanner does not",
      "queryPlanner is the one that returns timings",
      "Both always include scores for rejected plans",
      "executionStats cannot show which index won", 1),
    q("A SORT stage sits above the scan in the plan. What happened?",
      "Documents were sorted in memory, not by the index order",
      "The query was covered and read no documents",
      "The index prefix already matched the requested sort",
      "No documents in the collection matched the filter", 1),
    q("When is a query covered?",
      "When the index already holds every field the query returns",
      "When the collection itself was fully scanned",
      "Only when _id is included in the projection",
      "Only inside aggregate(), never inside find()", 1),
    q("What does every extra index cost?",
      "Extra work on writes, plus storage and memory",
      "Nothing at all, once the index has been built",
      "Only the first query that happens to use it",
      "A fresh election inside the replica set", 1),
]


# ---------------------------------------------------------------------------
# Module 7 — Introduction to Replication and Sharding
# ---------------------------------------------------------------------------

BANK[7] = [
    q("You need to stay online, not to split the data. What do you add?",
      "A replica set: copies, and failover if the primary is lost",
      "A shard key, which by itself also keeps the copies",
      "A bigger CPU on one server, which is horizontal scale",
      "mongos, which stores the collection on the router", 1),
    q("Who accepts writes in a replica set?",
      "The primary. Secondaries copy those writes",
      "Every secondary, so writes are spread out",
      "mongos, which also stores the collection data",
      "The config servers, one write per chunk", 1),
    q("What is the replication oplog?",
      "The primary's log of changes that secondaries replay",
      "A backup you restore after an accidental delete",
      "The map of which chunk ranges live on which shard",
      "A cache of the plans the query planner rejected", 1),
    q("What does a replica-set election require?",
      "Votes from a majority of the voting members",
      "A yes from every secondary, including ones that are down",
      "An operator command before any failover can finish",
      "The balancer to finish migrating a chunk", 1),
    q("What does read preference primary give you?",
      "The freshest data, from the member that accepts writes",
      "Any secondary, so the primary does less read work",
      "The nearest member, even when that copy is stale",
      "Reads that come only from a hidden analytics member", 1),
    q("Write concern majority means the write is acknowledged when?",
      "A majority of members have it, so failover can keep it",
      "The client asked for no acknowledgment at all",
      "Only the primary has it, and it may still be lost",
      "It is designed to be rolled back later", 1),
    q("Read concern local can return data that?",
      "Is the member's newest copy, but might still roll back",
      "A majority has already committed, so it will not roll back",
      "Has been deleted from every replica on purpose",
      "Lives only on a config server, not on a data member", 1),
    q("What is replication lag?",
      "How far a secondary's applied oplog trails the primary",
      "How long a chunk migration waits for the balancer",
      "The gap between RPO and RTO in a backup plan",
      "The delay before an index becomes unique", 1),
    q("A write with w:1 never reached a majority, then the primary was lost. Then?",
      "That write can be rolled back when the old primary rejoins",
      "Every secondary keeps that write permanently",
      "The config server restores it from a chunk map",
      "Read concern local makes that write durable", 1),
    q("What does mongos do in a sharded cluster?",
      "It routes requests and does not store collection data",
      "It is the only member allowed to accept writes",
      "It holds a full copy of every sharded collection",
      "It replaces the need for a replica set on each shard", 1),
    q("Why is a low-cardinality shard key like status a poor choice?",
      "Few distinct values make chunks that cannot split evenly",
      "It forces every query to include the shard key",
      "Hashed keys cannot be built on a string field",
      "Zone ranges can no longer pin data to a region", 1),
    q("What goes wrong with a monotonic shard key such as createdAt?",
      "New writes pile into the newest range, on one shard",
      "Range queries on that field become single-shard",
      "The balancer stops and elections cannot run",
      "Every document is copied to every shard", 1),
    q("What is the trade-off of hashing the shard key?",
      "Writes spread out, but ranges on that field scatter",
      "Range queries stay on one shard, and writes hotspot",
      "The shard key can no longer be a unique index",
      "mongos must store a full copy of every chunk", 1),
    q("orders is sharded on customerId. Which find is targeted?",
      "One that includes customerId, so one shard is enough",
      "One that filters only on order status",
      "One that sorts the whole collection by date",
      "One that omits the shard key and scans every shard", 1),
    q("A replica set spreads writes across its members. What is wrong with that claim?",
      "Only the primary accepts writes; secondaries copy them",
      "Secondaries accept writes whenever the primary is busy",
      "Sharding is what copies data for failover",
      "mongos accepts writes and stores them on the router", 1),
]


# ---------------------------------------------------------------------------
# Module 8 — Best Practices, Security, and Troubleshooting
# ---------------------------------------------------------------------------

BANK[8] = [
    q("Which data should stay embedded on the parent?",
      "Data that is bounded, owned, and read with the parent",
      "Data that grows without limit, such as every review",
      "A shared record that many documents point at",
      "Anything that used to be its own SQL table", 1),
    q("productId, product_id and prodId are all in use. What should you do?",
      "Pick one name and one BSON type for that idea",
      "Keep all three so old and new queries both work",
      "Let an index treat the three names as one field",
      "Store the id as text, number and date together", 1),
    q("The catalog price changes after checkout. What should the order show?",
      "The name and price copied onto the order at purchase",
      "Today's catalog price, looked up on every read",
      "No price, because money cannot be snapshotted",
      "Whatever the product document says right now", 1),
    q("What can $jsonSchema validation do on a collection?",
      "Reject writes that omit required fields or use wrong types",
      "Choose the shard key and the replica-set votes",
      "Replace backups, because bad writes cannot happen",
      "Turn a flexible schema back into SQL tables", 1),
    q("How should an application start a schema change?",
      "Read both the old shape and the new shape first",
      "Require the new field before any document is backfilled",
      "Drop the collection, then load only the new shape",
      "Turn validation to error on the first deploy", 1),
    q("A catalog page needs name and price. What should the query return?",
      "Only the fields that page actually uses",
      "Every field on the product, to stay flexible",
      "The full order history for that product",
      "Nothing until an aggregation $facet runs", 1),
    q("Where should $match sit in a reporting pipeline?",
      "Early, so later stages see fewer documents",
      "Only after $unwind, so totals stay large",
      "After $group, because filters cannot use indexes",
      "Nowhere, if the collection is already small", 1),
    q("Monthly revenue sums the order total after unwinding items. Risk?",
      "Each order total is counted once for every line",
      "Unwind removes tax before the sum",
      "The pipeline can no longer use $match",
      "Decimal128 totals become strings", 1),
    q("What is the evidence that an index actually helps a query?",
      "explain with executionStats, not a guess about field names",
      "The index exists in getIndexes, so the planner must use it",
      "The query returns rows, so the plan is fine",
      "A unique index, which always covers every find", 1),
    q("An application user should be granted which access?",
      "readWrite on its database, not a cluster-wide admin role",
      "clusterAdmin, so the app can manage users too",
      "No user, because the network is already private",
      "The Atlas login the operators use in the browser", 1),
    q("What protects data while it moves between client and server?",
      "TLS on every client connection and between members",
      "A strong shard key with high cardinality",
      "Hiding unused indexes before a release",
      "Storing passwords in the connection string", 1),
    q("Someone runs deleteMany on orders. Why doesn't replication save you?",
      "The delete is copied to every replica-set member",
      "Secondaries refuse deletes and keep the old orders",
      "The oplog stores a restorable backup automatically",
      "mongos blocks deletes unless a backup exists", 1),
    q("RPO is 15 minutes and RTO is 30 minutes. What do those mean?",
      "You may lose 15 minutes of data and be down 30 minutes",
      "You may be down 15 minutes and lose 30 minutes of data",
      "Backups run every 30 minutes and restore in 15",
      "Replication lag must stay under 15 seconds", 1),
    q("When is a backup actually proven?",
      "When a restore has been completed and checked",
      "When mongodump finishes without an error message",
      "When the replica set reports all members healthy",
      "When the backup file is larger than the database", 1),
    q("Order history jumps from 100 ms to 2.5 s. What is the useful first step?",
      "State that precise symptom, then gather evidence",
      "Restart mongod before looking at the query plan",
      "Shard the collection because any slowness means scale",
      "Grant the app clusterAdmin and try the query again", 1),
]
